import { execFile } from 'node:child_process';
import path from 'node:path';
import { mkdir, rename, rm, writeFile } from 'node:fs/promises';
import { promisify } from 'node:util';
import resolve from '@rollup/plugin-node-resolve';
import babel from '@rollup/plugin-babel';

const execFileAsync = promisify(execFile);
const packageRoot = process.cwd();
const consumerRoot = path.resolve(packageRoot, '..', '..', 'gohano-shinto');
const bundlesRoot = path.resolve(packageRoot, '..', '..', 'bundles');
const stableTarballPath = path.join(bundlesRoot, 'poon-ui.tgz');
const consumerRefreshPath = path.join(consumerRoot, 'client', 'poon-ui-refresh-client.js');

const packInstallPlugin = (watchMode) => ({
	name: 'pack-install',
	async writeBundle() {
		if (!watchMode) return;
		await execFileAsync('node', ['./scripts/generate-types.mjs']);
		await mkdir(bundlesRoot, {recursive: true});

		const {stdout} = await execFileAsync('npm', ['pack', '--json'], {cwd: packageRoot});
		const [{filename}] = JSON.parse(stdout);
		const tarballPath = path.join(packageRoot, filename);

		try {
			await rm(stableTarballPath, {force: true});
			await rename(tarballPath, stableTarballPath);
			await execFileAsync('npm', ['install', '--no-save', '--no-package-lock', stableTarballPath], {
				cwd: consumerRoot,
			});
			await writeFile(
				consumerRefreshPath,
				`// Generated by poon-ui watch to trigger Meteor refresh.\nimport { noop } from 'poon-ui';\nvoid noop;\nvoid ${Date.now()};\n`,
			);
		} finally {
			await rm(tarballPath, {force: true});
		}
	},
});

export default (commandLineArgs) => ({
	input: '.generated/index.js',
	watch: {
		exclude: [
			'dist/**',
			'.generated/**',
			'index.js',
			'index.d.ts',
		],
	},
	output: {
		file: 'dist/index.js',
		format: 'esm',
		sourcemap: true,
		generatedCode: {constBindings: true},
	},
	plugins: [
		resolve({
			browser: true,
			preferBuiltins: false,
		}),
		babel({
			babelHelpers: 'bundled',
			exclude: /node_modules/,
			presets: [
				['@babel/preset-react', {runtime: 'automatic'}],
			],
		}),
		packInstallPlugin(Boolean(commandLineArgs.watch)),
	],
	external: ['react', 'react/jsx-runtime', 'poon-router'],
});
